swagger: "2.0"
paths:
  /locations:
    get:
      responses:
        "200":
          description: ""
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
  "/menu/{id}":
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: ""
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
info:
  title: DiningService
  version: v3.0.0
